import Image from "next/image";
import { ArrowUpRight, Bell, Check, ChevronDown, Circle, CreditCard, Grid2X2, Layers, ListFilter, Package, Search, Settings2, Users, Workflow } from "lucide-react";

export type PreviewKind = "website" | "inventory" | "catalogue" | "erp" | "automation";

/** Illustrative interfaces, deliberately labeled as concepts, never client screenshots. */
export default function InterfacePreview({ kind = "website", className = "" }: { kind?: PreviewKind; className?: string }) {
  const isWebsite = kind === "website" || kind === "catalogue";
  return <div className={`interface-preview interface-${kind} ${className}`} aria-hidden="true">
    <div className="browser-bar"><span className="browser-dots"><i /><i /><i /></span><span>{isWebsite ? "Website preview" : "Workspace preview"}</span><span className="preview-concept">DESIGN CONCEPT</span></div>
    {isWebsite ? <div className="website-ui">
      <div className="website-ui-nav"><span>{kind === "website" ? "THE COLLECTION" : "Catalogue"}<i>.</i></span><span>Discover &nbsp; Collections &nbsp; Our story</span><ArrowUpRight size={15} /></div>
      {kind === "website" ? <div className="website-ui-hero"><div><span className="ui-eyebrow">CONSIDERED IN EVERY DETAIL</span><strong>Objects of<br /><em>quiet distinction.</em></strong><p>A considered collection.<br />An experience worth exploring.</p><span className="ui-link">Explore the collection <ArrowUpRight size={14} /></span></div><div className="website-ui-photo"><Image src="/images/jewellery.webp" alt="" fill sizes="(max-width: 600px) 55vw, 600px" /></div></div> : <div className="catalogue-ui-hero"><span className="ui-eyebrow">PRODUCTS / SPECIFICATIONS / ENQUIRIES</span><strong>Everything you need.<br /><em>Clearly presented.</em></strong><p>Find the right product. Compare the details. Start a conversation.</p><div className="catalogue-search"><Search size={15} />Search the catalogue<span>All categories <ChevronDown size={12} /></span></div><div className="catalogue-products">{["Product overview", "Technical specifications", "Request an enquiry"].map((label, i) => <div key={label}><span className="catalogue-product-number">0{i + 1}</span><span>{label}</span><ArrowUpRight size={15} /></div>)}</div></div>}
      <div className="website-ui-bottom"><span>Thoughtfully designed.</span><span>Seamlessly connected.</span><span>Built around you.</span></div>
    </div> : <div className="workspace-ui"><div className="workspace-sidebar"><span className="workspace-brand">workspace<i>.</i></span><span className="sidebar-selected"><Grid2X2 size={14} />Overview</span><span><Users size={14} />Customers</span><span><Package size={14} />Inventory</span><span><CreditCard size={14} />Payments</span><span><Workflow size={14} />Workflows</span><span className="sidebar-bottom"><Settings2 size={14} />Settings</span></div><div className="workspace-main"><div className="workspace-toolbar"><span>Your business, connected</span><div><Search size={14} /><Bell size={14} /><span className="ui-avatar">LS</span></div></div><div className="workspace-title"><div><span className="ui-eyebrow">{kind === "automation" ? "WORKFLOWS" : kind === "erp" ? "OPERATIONS" : "INVENTORY & BILLING"}</span><strong>{kind === "automation" ? "A little less manual." : kind === "erp" ? "One clear overview." : "Everything in order."}</strong></div><span className="workspace-date">Sample workspace</span></div>
      <div className="workspace-stats">{(kind === "automation" ? [["Trigger", "New enquiry"], ["Action", "Create customer"], ["Result", "Team notified"]] : [["Inventory", "Stock in sync"], ["Invoices", "Ready to review"], ["Customers", "One shared view"]]).map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong><small><Check size={10} />Connected</small></div>)}</div>
      {kind === "automation" ? <div className="mini-workflow"><span className="ui-eyebrow">ENQUIRY TO FOLLOW-UP</span>{["Enquiry received", "Customer created", "Notification sent", "Follow-up scheduled"].map((label, i) => <div key={label}><span className="mini-step-icon">{i === 0 ? <Workflow size={17} /> : <Check size={17} />}</span><span>{label}<small>{i === 0 ? "Website form" : "Automatic action"}</small></span><span className="mini-step-status">Ready</span></div>)}</div> : <div className="workspace-table"><div className="table-title"><strong>{kind === "erp" ? "Department activity" : "Recent activity"}</strong><ListFilter size={14} /></div><div className="table-row table-head"><span>{kind === "erp" ? "DEPARTMENT" : "ACTIVITY"}</span><span>WORKFLOW</span><span>STATUS</span></div>{(kind === "erp" ? [["Purchasing", "Purchase request", "In review"], ["Stores", "Stock transfer", "Ready"], ["Planning", "Schedule update", "In progress"], ["Administration", "Approval request", "Pending"]] : [["Order draft", "Sales", "In review"], ["Stock update", "Inventory", "Ready"], ["Invoice draft", "Billing", "Pending"], ["Customer enquiry", "CRM", "New"]]).map(([name, type, status]) => <div className="table-row" key={name}><span><Layers size={12} />{name}</span><span>{type}</span><span className="ui-status"><Circle size={5} fill="currentColor" />{status}</span></div>)}</div>}
      <div className="workspace-foot"><Check size={11} />One system. Less switching.<span>Illustrative data</span></div>
    </div></div>}
  </div>;
}
