import type { Metadata } from "next";
import { getSiteConfig } from "@/lib/site-config";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Hair Driver Review QR | LumenSpire",
  robots: { index: false, follow: false },
};

export default function HairDriverQrPage() {
  const config = getSiteConfig();
  return (
    <main className={styles.page}>
      <div className={styles.content}>
        <p className={styles.eyebrow}>LumenSpire Labs · QR utility</p>
        <h1>Hair Driver Review QR</h1>
        <p>Scan or download this QR for the permanent printed entry URL.</p>
        <div className={styles.qr}>
          {/* The image is generated by the local, fixed-destination QR endpoint. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={config.qrApiPath} alt="Hair Driver review QR code" width="360" height="360" />
        </div>
        <p className={styles.label}>Encoded destination</p>
        <p className={styles.url}>{config.qrRedirectUrl}</p>
        <p className={styles.note}>The production printed URL is {config.productionQrRedirectUrl}. The main site redirects it to the configured Hair Driver app.</p>
        <a className={styles.button} href={`${config.qrApiPath}?download=1`} download="hair-driver-review-qr.svg">Download SVG</a>
        <p className={styles.warning}>Do not print the final acrylic stand until production routing and real phone scans are verified.</p>
      </div>
    </main>
  );
}
